#if !canImport(ObjectiveC)
import XCTest

extension XcodeStringsParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcodeStringsParserTests = [
        ("testDoubleStarAtEndOfComment", testDoubleStarAtEndOfComment),
        ("testEmpty", testEmpty),
        ("testFail1", testFail1),
        ("testFail2", testFail2),
        ("testFail3", testFail3),
        ("testFail4", testFail4),
        ("testFail5", testFail5),
        ("testFail6", testFail6),
        ("testFail7", testFail7),
        ("testFail8", testFail8),
        ("testFail9", testFail9),
        ("testNoValues1", testNoValues1),
        ("testNoValues2", testNoValues2),
        ("testNoValues3", testNoValues3),
        ("testParseSimpleXcodeStringsFile1", testParseSimpleXcodeStringsFile1),
        ("testParseSimpleXcodeStringsFile2", testParseSimpleXcodeStringsFile2),
        ("testParseSimpleXcodeStringsFile3", testParseSimpleXcodeStringsFile3),
        ("testParseSimpleXcodeStringsFile4", testParseSimpleXcodeStringsFile4),
        ("testParseSimpleXcodeStringsFile5", testParseSimpleXcodeStringsFile5),
        ("testParseTwoValuesXcodeStringsFile", testParseTwoValuesXcodeStringsFile),
        ("testParseWeirdXcodeStringsFile1", testParseWeirdXcodeStringsFile1),
        ("testParseWeirdXcodeStringsFile2", testParseWeirdXcodeStringsFile2),
        ("testParseWeirdXcodeStringsFile3", testParseWeirdXcodeStringsFile3),
        ("testParseWeirdXcodeStringsFile4", testParseWeirdXcodeStringsFile4),
        ("testStarAtEndOfComment", testStarAtEndOfComment),
        ("testStarInComment", testStarInComment),
        ("testWhiteAfterValues", testWhiteAfterValues),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XcodeStringsParserTests.__allTests__XcodeStringsParserTests),
    ]
}
#endif
